config_version: 1

sdk:
  config_files:
    robot: robot_m750.yaml
    safety: safety.yaml
    logging: logging.yaml

  adapter:
    type: replay
    replay:
      replay_file: ../../benchmarks/sample_joint_states.jsonl
      loop: true
