config_version: 1

robot:
  name: myarm_m750
  joint_names:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_flex_joint
    - forearm_roll_joint
    - wrist_flex_joint
    - wrist_roll_joint

  model:
    urdf_path: ../src/resources/myarm_m750_kinematic.urdf
    base_link: base_link
    end_link: tool0
    resource_sha256: 0927796df0a9ada2385f5f0916bb7582f1967cf2f1ab047e6a2f2fe96c612d24
    kinematic_contract_sha256: ecc19f88b1f74951cd8f2db427ad41ff3d6c9f7ec1304648d43f85322f4b9c52

  joint_mapping:
    shoulder_pan_joint:
      offset_degree: 0.0
      direction: 1
    shoulder_lift_joint:
      offset_degree: 10.0
      direction: 1
    elbow_flex_joint:
      offset_degree: -10.0
      direction: 1
    forearm_roll_joint:
      offset_degree: 0.0
      direction: 1
    wrist_flex_joint:
      offset_degree: 0.0
      direction: 1
    wrist_roll_joint:
      offset_degree: 0.0
      direction: 1

  runtime:
    command_rate_hz: 5.0
    state_rate_hz: 5.0
