<?xml version="1.0"?>
<package format="3">
  <name>myarm_m750_visualization</name>
  <version>0.1.1</version>
  <description>RViz2 Host PC visualization and debug markers.</description>
  <maintainer email="khoa@example.invalid">Nguyen Hoang Dang Khoa</maintainer>
  <license>LicenseRef-Proprietary</license>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>myarm_m750_description</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
