<?xml version="1.0"?>
<package format="3">
  <name>myarm_m750_bringup</name>
  <version>0.2.0</version>
  <description>Explicit Fast DDS Jetson-side MyArm M750 bring-up.</description>
  <maintainer email="khoa@example.invalid">Nguyen Hoang Dang Khoa</maintainer>
  <license>LicenseRef-Proprietary</license>
  <exec_depend>myarm_m750_description</exec_depend>
  <exec_depend>myarm_m750_driver</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rmw_fastrtps_cpp</exec_depend>
  <test_depend>ament_cmake_test</test_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
